### PR TITLE
Returns calculated values as is

### PR DESCRIPTION
**Pull request by alexanderwallin**
I wanted to use this for a hearing test, which needs near-silence audio. The `< -40` check and the rounding prevented that, so I created this PR. Rounding and thresholds can easily be done yourself if you need!

### CODE REVIEW

**Comment by alexanderwallin** [comment]
Would you have a look at this, @mmckegg? I'm using this in a fair amount of projects, now copying and pasting the functions.

I can't personally decipher that failed test, tho! 😐

**Comment by mmckegg** [comment]
@alexanderwallin 

That's a good point! This was extracted out of a project that had very specific needs. Thanks for the PR, will get the changes published later today as a major release.

**Comment by mmckegg** [comment]
Whoops, I don't seem to have write access to the module to merge the PR and push the latest tags.

@audiojs/core could you give me write access or transfer back to me?

@alexanderwallin I have published this as v2.0.0!

**Comment by jamen** [comment]
@mmckegg Changed all existing repos to writable and set that to default. Thanks.

**Comment by alexanderwallin** [comment]
Thanks, guys!

**Pull request merged**
